print('Expressie    Uitkomst    Type')
print('5            5           Integer')
print('5.0          5.0         Float')
print('5 % 2        1           Integer')
print('5 > 1	    True        Boolean')
print('"5"          5       	String')
print('5 * 2        10          Integer')
